// Built-in catalogue of news sources. Entries marked `true` are switched on
// for new users; everything else can be turned on in Settings → Sources.
// Telegram entries are public channel usernames (read via t.me/s/<name>).

const GROUPS = {
  'Top stories': [
    ['BBC News', 'https://feeds.bbci.co.uk/news/rss.xml', true],
    ['BBC World', 'https://feeds.bbci.co.uk/news/world/rss.xml', true],
    ['NPR News', 'https://feeds.npr.org/1001/rss.xml', true],
    ['The Guardian World', 'https://www.theguardian.com/world/rss', true],
    ['Al Jazeera', 'https://www.aljazeera.com/xml/rss/all.xml', true],
    ['New York Times', 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', true],
    ['NYT World', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml'],
    ['Washington Post World', 'https://feeds.washingtonpost.com/rss/world'],
    ['Sky News', 'https://feeds.skynews.com/feeds/rss/home.xml'],
    ['Sky News World', 'https://feeds.skynews.com/feeds/rss/world.xml'],
    ['Euronews', 'https://www.euronews.com/rss'],
    ['France 24', 'https://www.france24.com/en/rss', true],
    ['DW News', 'https://rss.dw.com/rdf/rss-en-all', true],
    ['RFI English', 'https://www.rfi.fr/en/rss'],
    ['The Conversation', 'https://theconversation.com/global/articles.atom'],
    ['Christian Science Monitor', 'https://rss.csmonitor.com/feeds/all'],
    ['Time', 'https://time.com/feed/'],
    ['Newsweek', 'https://www.newsweek.com/rss'],
  ],
  'United States': [
    ['NPR Politics', 'https://feeds.npr.org/1014/rss.xml'],
    ['NYT U.S.', 'https://rss.nytimes.com/services/xml/rss/nyt/US.xml'],
    ['NYT Politics', 'https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml'],
    ['Washington Post Politics', 'https://feeds.washingtonpost.com/rss/politics'],
    ['The Guardian US', 'https://www.theguardian.com/us-news/rss'],
    ['CBS News', 'https://www.cbsnews.com/latest/rss/main'],
    ['ABC News', 'https://abcnews.go.com/abcnews/topstories'],
    ['NBC News', 'https://feeds.nbcnews.com/nbcnews/public/news'],
    ['Fox News', 'https://moxie.foxnews.com/google-publisher/latest.xml'],
    ['PBS NewsHour', 'https://www.pbs.org/newshour/feeds/rss/headlines', true],
    ['Politico', 'https://rss.politico.com/politics-news.xml'],
    ['The Hill', 'https://thehill.com/feed/'],
    ['Axios', 'https://api.axios.com/feed/'],
    ['Vox', 'https://www.vox.com/rss/index.xml'],
    ['The Atlantic', 'https://www.theatlantic.com/feed/all/'],
    ['The New Yorker', 'https://www.newyorker.com/feed/news'],
    ['ProPublica', 'https://www.propublica.org/feeds/propublica/main'],
  ],
  'United Kingdom': [
    ['BBC UK', 'https://feeds.bbci.co.uk/news/uk/rss.xml'],
    ['BBC Politics', 'https://feeds.bbci.co.uk/news/politics/rss.xml'],
    ['The Guardian UK', 'https://www.theguardian.com/uk-news/rss'],
    ['Guardian Politics', 'https://www.theguardian.com/politics/rss'],
    ['The Independent', 'https://www.independent.co.uk/news/rss'],
    ['The Telegraph', 'https://www.telegraph.co.uk/rss.xml'],
  ],
  Europe: [
    ['Politico Europe', 'https://www.politico.eu/feed/'],
    ['Kyiv Independent', 'https://kyivindependent.com/rss/'],
    ['The Moscow Times', 'https://www.themoscowtimes.com/rss/news'],
  ],
  'Asia & Pacific': [
    ['South China Morning Post', 'https://www.scmp.com/rss/91/feed'],
    ['The Japan Times', 'https://www.japantimes.co.jp/feed/'],
    ['Times of India', 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms'],
    ['The Hindu', 'https://www.thehindu.com/news/feeder/default.rss'],
    ['NDTV', 'https://feeds.feedburner.com/ndtvnews-top-stories'],
    ['ABC News Australia', 'https://www.abc.net.au/news/feed/45910/rss.xml', true],
    ['Sydney Morning Herald', 'https://www.smh.com.au/rss/feed.xml'],
    ['RNZ', 'https://www.rnz.co.nz/rss/national.xml'],
  ],
  Americas: [
    ['CBC News', 'https://www.cbc.ca/webfeed/rss/rss-topstories', true],
    ['CBC World', 'https://www.cbc.ca/webfeed/rss/rss-world'],
    ['Global News', 'https://globalnews.ca/feed/'],
  ],
  'Middle East & Africa': [
    ['Middle East Eye', 'https://www.middleeasteye.net/rss'],
    ['The Times of Israel', 'https://www.timesofisrael.com/feed/'],
    ['AllAfrica', 'https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf'],
  ],
  Business: [
    ['BBC Business', 'https://feeds.bbci.co.uk/news/business/rss.xml'],
    ['NPR Business', 'https://feeds.npr.org/1006/rss.xml'],
    ['NYT Business', 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml'],
    ['Guardian Business', 'https://www.theguardian.com/business/rss'],
    ['CNBC', 'https://www.cnbc.com/id/100003114/device/rss/rss.html', true],
    ['CNBC World', 'https://www.cnbc.com/id/100727362/device/rss/rss.html'],
    ['MarketWatch', 'https://feeds.content.dowjones.io/public/rss/mw_topstories'],
    ['WSJ World', 'https://feeds.content.dowjones.io/public/rss/RSSWorldNews'],
    ['WSJ Markets', 'https://feeds.content.dowjones.io/public/rss/RSSMarketsMain'],
    ['Financial Times', 'https://www.ft.com/rss/home'],
    ['The Economist', 'https://www.economist.com/latest/rss.xml'],
    ['Business Insider', 'https://feeds.businessinsider.com/custom/all'],
    ['Fortune', 'https://fortune.com/feed/'],
    ['Forbes Business', 'https://www.forbes.com/business/feed/'],
    ['Fast Company', 'https://www.fastcompany.com/latest/rss'],
    ['Yahoo Finance', 'https://finance.yahoo.com/news/rssindex'],
    ['Investing.com', 'https://www.investing.com/rss/news.rss'],
    ['CoinDesk', 'https://www.coindesk.com/arc/outboundfeeds/rss/'],
    ['Cointelegraph', 'https://cointelegraph.com/rss'],
  ],
  Tech: [
    ['Ars Technica', 'https://feeds.arstechnica.com/arstechnica/index', true],
    ['The Verge', 'https://www.theverge.com/rss/index.xml', true],
    ['TechCrunch', 'https://techcrunch.com/feed/', true],
    ['Hacker News', 'https://hnrss.org/frontpage', true],
    ['Wired', 'https://www.wired.com/feed/rss'],
    ['Engadget', 'https://www.engadget.com/rss.xml'],
    ['MIT Technology Review', 'https://www.technologyreview.com/feed/'],
    ['BBC Technology', 'https://feeds.bbci.co.uk/news/technology/rss.xml'],
    ['NYT Technology', 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml'],
    ['Guardian Technology', 'https://www.theguardian.com/technology/rss'],
    ['CNBC Tech', 'https://www.cnbc.com/id/19854910/device/rss/rss.html'],
    ['The Register', 'https://www.theregister.com/headlines.atom'],
    ['Gizmodo', 'https://gizmodo.com/rss'],
    ['ZDNET', 'https://www.zdnet.com/news/rss.xml'],
    ['CNET', 'https://www.cnet.com/rss/news/'],
    ["Tom's Hardware", 'https://www.tomshardware.com/feeds/all'],
    ['VentureBeat', 'https://venturebeat.com/feed/'],
    ['Techmeme', 'https://www.techmeme.com/feed.xml'],
    ['Slashdot', 'https://rss.slashdot.org/Slashdot/slashdotMain'],
    ['Lobsters', 'https://lobste.rs/rss'],
    ['9to5Mac', 'https://9to5mac.com/feed/'],
    ['9to5Google', 'https://9to5google.com/feed/'],
    ['MacRumors', 'https://feeds.macrumors.com/MacRumors-All'],
    ['Android Authority', 'https://www.androidauthority.com/feed/'],
    ['BleepingComputer', 'https://www.bleepingcomputer.com/feed/'],
    ['Krebs on Security', 'https://krebsonsecurity.com/feed/'],
    ['The Hacker News', 'https://feeds.feedburner.com/TheHackersNews'],
    ['GitHub Blog', 'https://github.blog/feed/'],
    ['Google AI Blog', 'https://blog.google/technology/ai/rss/'],
    ['OpenAI News', 'https://openai.com/news/rss.xml'],
    ['Product Hunt', 'https://www.producthunt.com/feed'],
  ],
  Science: [
    ['ScienceDaily', 'https://www.sciencedaily.com/rss/all.xml', true],
    ['NASA', 'https://www.nasa.gov/feed/', true],
    ['New Scientist', 'https://www.newscientist.com/feed/home/'],
    ['Scientific American', 'http://rss.sciam.com/ScientificAmerican-Global'],
    ['Nature', 'https://www.nature.com/nature.rss'],
    ['Science News (AAAS)', 'https://www.science.org/rss/news_current.xml'],
    ['Phys.org', 'https://phys.org/rss-feed/'],
    ['Space.com', 'https://www.space.com/feeds/all'],
    ['Live Science', 'https://www.livescience.com/feeds/all'],
    ['Quanta Magazine', 'https://www.quantamagazine.org/feed/'],
    ['Smithsonian', 'https://www.smithsonianmag.com/rss/latest_articles/'],
    ['Universe Today', 'https://www.universetoday.com/feed/'],
    ['BBC Science', 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml'],
    ['NPR Science', 'https://feeds.npr.org/1007/rss.xml'],
    ['NYT Science', 'https://rss.nytimes.com/services/xml/rss/nyt/Science.xml'],
    ['Guardian Science', 'https://www.theguardian.com/science/rss'],
  ],
  Climate: [
    ['Inside Climate News', 'https://insideclimatenews.org/feed/', true],
    ['Carbon Brief', 'https://www.carbonbrief.org/feed/'],
    ['Grist', 'https://grist.org/feed/'],
    ['Yale Environment 360', 'https://e360.yale.edu/feed.xml'],
    ['Mongabay', 'https://news.mongabay.com/feed/'],
    ['Guardian Environment', 'https://www.theguardian.com/environment/rss'],
    ['NYT Climate', 'https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml'],
    ['Electrek', 'https://electrek.co/feed/'],
    ['CleanTechnica', 'https://cleantechnica.com/feed/'],
  ],
  Health: [
    ['STAT', 'https://www.statnews.com/feed/', true],
    ['KFF Health News', 'https://kffhealthnews.org/feed/'],
    ['WHO News', 'https://www.who.int/rss-feeds/news-english.xml'],
    ['NIH News', 'https://www.nih.gov/news-releases/feed.xml'],
    ['BBC Health', 'https://feeds.bbci.co.uk/news/health/rss.xml'],
    ['NPR Health', 'https://feeds.npr.org/1128/rss.xml'],
    ['NYT Health', 'https://rss.nytimes.com/services/xml/rss/nyt/Health.xml'],
  ],
  Sports: [
    ['ESPN', 'https://www.espn.com/espn/rss/news', true],
    ['ESPN NFL', 'https://www.espn.com/espn/rss/nfl/news'],
    ['ESPN NBA', 'https://www.espn.com/espn/rss/nba/news'],
    ['ESPN Soccer', 'https://www.espn.com/espn/rss/soccer/news'],
    ['BBC Sport', 'https://feeds.bbci.co.uk/sport/rss.xml'],
    ['BBC Football', 'https://feeds.bbci.co.uk/sport/football/rss.xml'],
    ['Sky Sports', 'https://www.skysports.com/rss/12040'],
    ['Guardian Sport', 'https://www.theguardian.com/sport/rss'],
    ['NYT Sports', 'https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml'],
    ['CBS Sports', 'https://www.cbssports.com/rss/headlines/'],
    ['Yahoo Sports', 'https://sports.yahoo.com/rss/'],
    ['Autosport F1', 'https://www.autosport.com/rss/f1/news/'],
    ['ESPNcricinfo', 'https://www.espncricinfo.com/rss/content/story/feeds/0.xml'],
  ],
  'Culture & games': [
    ['Variety', 'https://variety.com/feed/', true],
    ['The Hollywood Reporter', 'https://www.hollywoodreporter.com/feed/'],
    ['Deadline', 'https://deadline.com/feed/'],
    ['Rolling Stone', 'https://www.rollingstone.com/feed/'],
    ['Pitchfork', 'https://pitchfork.com/feed/feed-news/rss'],
    ['BBC Entertainment', 'https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml'],
    ['Guardian Culture', 'https://www.theguardian.com/culture/rss'],
    ['NYT Arts', 'https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml'],
    ['Colossal', 'https://www.thisiscolossal.com/feed/'],
    ['IGN', 'https://feeds.feedburner.com/ign/all'],
    ['Polygon', 'https://www.polygon.com/rss/index.xml'],
    ['Kotaku', 'https://kotaku.com/rss'],
    ['Eurogamer', 'https://www.eurogamer.net/feed'],
  ],
  'Good news': [
    ['Good News Network', 'https://www.goodnewsnetwork.org/feed/', true],
    ['Positive News', 'https://www.positive.news/feed/'],
  ],
  'Fact checks': [
    ['PolitiFact', 'https://www.politifact.com/rss/all/'],
    ['Snopes', 'https://www.snopes.com/feed/'],
  ],
  Reddit: [
    ['r/worldnews', 'https://www.reddit.com/r/worldnews/.rss'],
    ['r/news', 'https://www.reddit.com/r/news/.rss'],
    ['r/technology', 'https://www.reddit.com/r/technology/.rss'],
    ['r/science', 'https://www.reddit.com/r/science/.rss'],
    ['r/UpliftingNews', 'https://www.reddit.com/r/UpliftingNews/.rss'],
  ],
  Telegram: [
    ['Telegram News', 'telegram'],
    ['Pavel Durov', 'durov'],
    ['Ukraine NOW', 'UkraineNow'],
    ['NEXTA Live', 'nexta_live'],
    ['BBC News Russian', 'bbcrussian'],
    ['Cointelegraph', 'cointelegraph'],
  ],
};

function slug(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

const CATALOG = Object.entries(GROUPS).flatMap(([group, entries]) =>
  entries.map(([name, url, on]) => {
    const telegram = group === 'Telegram';
    return {
      id: telegram ? `tg-${url.toLowerCase()}` : slug(`${name}`),
      name,
      url,
      type: telegram ? 'telegram' : 'rss',
      group,
      defaultOn: Boolean(on),
    };
  }),
);

module.exports = { CATALOG, GROUP_ORDER: [...Object.keys(GROUPS), 'Added by you'], slug };
